# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lynxdb < Formula
  desc "Open-source log analytics database. Single binary. SPL2 query language."
  homepage "https://lynxdb.org"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.2/lynxdb-v0.0.2-darwin-amd64.tar.gz"
      sha256 "065415d9c2a9ab9dfb12a91d58679d367f34666ca17f4b17c5388e99aa2b0353"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.2/lynxdb-v0.0.2-darwin-arm64.tar.gz"
      sha256 "1a0b8a9511075712b77f6b9525b780cf3335ae942604b219c647ee1a33a407b1"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.2/lynxdb-v0.0.2-linux-amd64.tar.gz"
      sha256 "bdec2be949d394a02eea5680c537a8a1c960bd6fe1f01667a5ad9f8e810c4570"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.2/lynxdb-v0.0.2-linux-arm64.tar.gz"
      sha256 "67ac1e3824f437f07818bd571cddfb9d68e1d9a1a1eaa8a5eeae82ab3b280fcd"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  test do
    system "#{bin}/lynxdb", "version"
  end
end
