# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lynxdb < Formula
  desc "Open-source log analytics database. Single binary. SPL2 query language."
  homepage "https://lynxdb.org"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.1/lynxdb-v0.0.1-darwin-amd64.tar.gz"
      sha256 "348a34c71637317874b94efb421165e0cb7799da7cb77fcd10e62139f1190dc5"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.1/lynxdb-v0.0.1-darwin-arm64.tar.gz"
      sha256 "9310580fe2fddaf7f0eed7caddca52db4a692a50c809acbe11b0f1c9fba96596"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.1/lynxdb-v0.0.1-linux-amd64.tar.gz"
      sha256 "6514c01bbb2fb8d42fecde3e47ebb5e87f62924630177acdfb236d3234d4a9b8"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.0.1/lynxdb-v0.0.1-linux-arm64.tar.gz"
      sha256 "20f1f427180c4ea7532d27100a8a5cc1ec2258f53e634cf90700f419288a5afc"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  test do
    system "#{bin}/lynxdb", "version"
  end
end
