# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lynxdb < Formula
  desc "Open-source log analytics database with a single binary and SPL2 query language"
  homepage "https://lynxdb.org"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.3/lynxdb-v0.2.3-darwin-amd64.tar.gz"
      sha256 "03cabf49cf03e39fd6fb3de4478dd8da1aae52ee2b1dd590af7639f50f3bcc76"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.3/lynxdb-v0.2.3-darwin-arm64.tar.gz"
      sha256 "71e30a8f147a1656b3f5b3d546af92b53431539f8f2d6f22a5b0ef2bb50ac308"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.3/lynxdb-v0.2.3-linux-amd64.tar.gz"
      sha256 "676f2237b5131f46eb380f671ee166388d22c90f4fde04367708034ab60cfbb7"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.3/lynxdb-v0.2.3-linux-arm64.tar.gz"
      sha256 "c97dfc8ea73d643824cac52516bd0d35bf7541e2fdaf71981aae645381b4cb9c"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  test do
    system bin/"lynxdb", "version"
  end
end
