# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lynxdb < Formula
  desc "Open-source log analytics database with a single binary and SPL2 query language"
  homepage "https://lynxdb.org"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.0/lynxdb-v0.2.0-darwin-amd64.tar.gz"
      sha256 "6c8e33e5a85f5a1af76b87817d63da8e3622e6e2e8d01e29f69a69825a0924f0"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.0/lynxdb-v0.2.0-darwin-arm64.tar.gz"
      sha256 "c586cafbb7e7d1906bd4b7d12e671a65571e7bb9fcfa4a5c0ad980d3b8356380"

      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.0/lynxdb-v0.2.0-linux-amd64.tar.gz"
      sha256 "8c84c325e33c4083353839f75a88f93ee597271e919c669d41de924d2a2ce413"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lynxbase/lynxdb/releases/download/v0.2.0/lynxdb-v0.2.0-linux-arm64.tar.gz"
      sha256 "c3feffa484121c765ace1c60570578a0ee4d47162b4f55db97d071401e378575"
      define_method(:install) do
        bin.install "lynxdb"
      end
    end
  end

  test do
    system bin/"lynxdb", "version"
  end
end
